### ISSUE TITLE
Morning Session Code Review

### ISSUE THREAD

**Issue by BonkeGcobo** [Hombre2014/ToDoList#16]
@BonkeGcobo
Job well done Yuriy the project work as it should, The readme is well-documented 🥇  keep up the good work 💯

**Comment by kingqabil** [comment]
@kingqabil
Well done Yuri keep coding!

**Comment by abdessalem1998** [comment]
@abdessalem1998
Amazing implementation of testing cases congratulations :)

**Comment by Hombre2014** [comment]
Thanks!
