### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by anuarshaidenov** [Hombre2014/ToDoList#3]
## Highlights:
- You separated the files and exported necessary functions ✅
- Your styles look great ✅
### However there are some issues to address:
- The list items are not appearing.

**Comment by kingqabil** [comment]
Your list items are not appearing check it

**Comment by Hombre2014** [comment]
Thanks for your suggestions and cooperation. The changes have been implemented and the problem disappeared.
